---
- name: Configurar usuário acessotr com shell restrito e sudo limitado
  hosts: all
  become: true

  vars:
    user_name: acessotr
    user_home: "/home/acessotr"

  tasks:

    - name: Garantir que /bin/rbash existe como link simbólico para /bin/bash
      file:
        src: /bin/bash
        dest: /bin/rbash
        state: link
        force: yes

    - name: Criar o usuário acessotr com shell restrito (rbash) sem senha
      user:
        name: "{{ user_name }}"
        shell: /bin/rbash
        create_home: yes
        password_lock: yes

    - name: Criar diretório bin pessoal para comandos permitidos
      file:
        path: "{{ user_home }}/bin"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'

    - name: Criar links simbólicos para comandos permitidos
      file:
        src: "{{ item.src }}"
        dest: "{{ user_home }}/bin/{{ item.name }}"
        state: link
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
      loop:
        - { name: ls,         src: /bin/ls }
        - { name: cp,         src: /bin/cp }
        - { name: vim,        src: /usr/bin/vim }
        - { name: systemctl,  src: /bin/systemctl }
        - { name: ifconfig,   src: /sbin/ifconfig }

    - name: Configurar .bash_profile com PATH restrito
      copy:
        dest: "{{ user_home }}/.bash_profile"
        content: 'PATH=$HOME/bin'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Adicionar regras sudo limitadas para acessotr
      copy:
        dest: "/etc/sudoers.d/{{ user_name }}"
        content: |
          {{ user_name }} ALL=(ALL) NOPASSWD: /bin/ls, /bin/cp, /usr/bin/vim, /bin/systemctl, /sbin/ifconfig
        owner: root
        group: root
        mode: '0440'
