---
- name: Atualizar cert_file e priv_key_file diretamente do arquivo conf
  hosts: all
  become: true

  vars:
    conf_file: "/etc/asterisk/pjsip_transport.conf"
    db_name: "asterisk"

  tasks:

    - name: Ler cert_file direto do arquivo
      shell: "grep '^cert_file' {{ conf_file }} | cut -d '=' -f2 | tr -d ' '"
      register: cert_line

    - name: Ler priv_key_file direto do arquivo
      shell: "grep '^priv_key_file' {{ conf_file }} | cut -d '=' -f2 | tr -d ' '"
      register: key_line

    - name: Atualizar cert_file no banco (grupo transport)
      shell: >
        mysql -u {{ lookup('env','DB_USER') }}
        -p{{ lookup('env','DB_PASSWORD') }}
        -D {{ db_name }}
        -e "UPDATE pjsip_configs
            SET value='{{ cert_line.stdout }}'
            WHERE field='cert_file' AND TRIM(`group`)='transport';"

    - name: Atualizar priv_key_file no banco (grupo transport)
      shell: >
        mysql -u {{ lookup('env','DB_USER') }}
        -p{{ lookup('env','DB_PASSWORD') }}
        -D {{ db_name }}
        -e "UPDATE pjsip_configs
            SET value='{{ key_line.stdout }}'
            WHERE field='priv_key_file' AND TRIM(`group`)='transport';"

    - debug:
        msg:
          - "cert_file => {{ cert_line.stdout }}"
          - "priv_key_file => {{ key_line.stdout }}"
