---
- name: Sincronizar certificados TLS do Asterisk
  hosts: all
  become: true

  vars:
    conf_file: "/etc/asterisk/pjsip_transport.conf"
    db_name: "asterisk"

  tasks:

    - name: Ler valor do cert_file
      command: "grep '^cert_file' {{ conf_file }}"
      register: cert_line

    - name: Ler valor do priv_key_file
      command: "grep '^priv_key_file' {{ conf_file }}"
      register: key_line

    - name: Extrair caminhos
      set_fact:
        cert_path: "{{ cert_line.stdout.split('=')[1] | trim }}"
        key_path: "{{ key_line.stdout.split('=')[1] | trim }}"

    # 1️⃣ REMOVER QUALQUER cert_file SEM GROUP
    - name: Remover cert_file com group NULL
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          DELETE FROM pjsip_configs
          WHERE field='cert_file'
            AND (`group` IS NULL OR TRIM(`group`)='');"

    # 1️⃣ REMOVER QUALQUER priv_key_file SEM GROUP
    - name: Remover priv_key_file com group NULL
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          DELETE FROM pjsip_configs
          WHERE field='priv_key_file'
            AND (`group` IS NULL OR TRIM(`group`)='');"

    # 2️⃣ GARANTIR QUE A LINHA CERTA EXISTE
    - name: Criar cert_file se não existir
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          INSERT IGNORE INTO pjsip_configs (field, value, `group`)
          VALUES ('cert_file', '', 'transport');"

    - name: Criar priv_key_file se não existir
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          INSERT IGNORE INTO pjsip_configs (field, value, `group`)
          VALUES ('priv_key_file', '', 'transport');"

    # 3️⃣ NOW update the correct ones
    - name: Atualizar cert_file
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          UPDATE pjsip_configs
          SET value='{{ cert_path }}'
          WHERE field='cert_file' AND `group`='transport';"

    - name: Atualizar priv_key_file
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          UPDATE pjsip_configs
          SET value='{{ key_path }}'
          WHERE field='priv_key_file' AND `group`='transport';"

    - name: Exibir resultado
      debug:
        msg:
          - "cert_file => {{ cert_path }}"
          - "priv_key_file => {{ key_path }}"
