- name: Emitir certificados Let's Encrypt para múltiplos domínios (www + sem-www)
  hosts: all
  become: yes

  vars:
    email_cert: "certificados@uniontelecom.com.br"
    log_path: "/var/log/certbot-renew.log"
    dominios:
      - asttecom.com.br
      - atatelecom.com.br
      - ativador.uscall.com.br
      - comercial.uniontelecom.com.br
      - leads.nuvemfone.com.br
      - leads.uniontel.com.br
      - leads.uniontelecom.com.br
      - leads.uscall.com.br
      - negocios.uniontelecom.com.br
      - omnichan.uscall.com.br
      - portaldev.uniontelecom.com.br
      - portal.uniontelecom.com.br
      - unionfone.com.br
      - uniontel.com.br
      - virtualportsistemas.com.br
      - virtualport.uniontelecom.com.br
      - webphone.uscall.com.br
      - wiki.uniontelecom.com.br
      - www.uniontelecom.com.br
      - www.uscall.com.br

  tasks:
    - name: Instalar dependências do Certbot
      apt:
        name:
          - software-properties-common
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Emitir certificados para cada domínio (com e sem www)
      loop: "{{ dominios }}"
      ansible.builtin.shell: |
        DOM_SEM_WWW=$(echo {{ item }} | sed 's/^www\.//')
        echo "==== [$(date)] Emitindo certificado para $DOM_SEM_WWW e www.$DOM_SEM_WWW ====" >> {{ log_path }}
        certbot --nginx -d $DOM_SEM_WWW -d www.$DOM_SEM_WWW \
          --email {{ email_cert }} \
          --agree-tos --non-interactive --redirect --expand >> {{ log_path }} 2>&1
      ignore_errors: yes

    - name: Recarregar Nginx após emissão dos certificados
      service:
        name: nginx
        state: reloaded

    - name: Exibir últimas linhas do log
      shell: tail -n 20 {{ log_path }}
      register: log_saida
      ignore_errors: true

    - debug:
        msg: "{{ log_saida.stdout_lines | default('Sem log gerado ainda.') }}"
