---
- name: Sincronizar certificados TLS do Asterisk
  hosts: all
  become: true

  vars:
    conf_file: "/etc/asterisk/pjsip_transport.conf"
    db_name: "asterisk"

  tasks:

    # 1. Ler linhas de cert_file e priv_key_file do arquivo de transporte
    - name: Ler valor do cert_file
      command: "grep '^cert_file' {{ conf_file }}"
      register: cert_line

    - name: Ler valor do priv_key_file
      command: "grep '^priv_key_file' {{ conf_file }}"
      register: key_line

    # 2. Extrair apenas o caminho (tudo após o "=")
    - name: Extrair caminhos
      set_fact:
        cert_path: "{{ cert_line.stdout.split('=')[1] | trim }}"
        key_path: "{{ key_line.stdout.split('=')[1] | trim }}"

    # 3. Remover duplicatas na tabela para manter apenas o grupo 'transport'
    - name: Remover duplicatas de cert_file
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "DELETE FROM pjsip_configs
            WHERE field='cert_file' AND (`group` IS NULL OR `group`!='transport');"

    - name: Remover duplicatas de priv_key_file
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "DELETE FROM pjsip_configs
            WHERE field='priv_key_file' AND (`group` IS NULL OR `group`!='transport');"

    # 4. Atualizar apenas o registro correto (field + group)
    - name: Atualizar cert_file correto
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "UPDATE pjsip_configs SET value='{{ cert_path }}'
            WHERE field='cert_file' AND `group`='transport';"

    - name: Atualizar priv_key_file correto
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "UPDATE pjsip_configs SET value='{{ key_path }}'
            WHERE field='priv_key_file' AND `group`='transport';"

    # 5. Exibir resultado
    - name: Exibir resultado
      debug:
        msg:
          - "cert_file atualizado para: {{ cert_path }}"
          - "priv_key_file atualizado para: {{ key_path }}"
