---
- name: Atualizar certificados TLS do Asterisk (dinâmico por servidor)
  hosts: all
  become: true

  vars:
    conf_file: "/etc/asterisk/pjsip_transport.conf"
    db_name: "asterisk"

  tasks:

    - name: Ler cert_file local
      command: "grep '^cert_file' {{ conf_file }}"
      register: cert_line

    - name: Ler priv_key_file local
      command: "grep '^priv_key_file' {{ conf_file }}"
      register: key_line

    - name: Extrair caminhos dos arquivos
      set_fact:
        cert_path: "{{ cert_line.stdout.split('=')[1] | trim }}"
        key_path: "{{ key_line.stdout.split('=')[1] | trim }}"

    - name: Atualizar cert_file no grupo transport
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          UPDATE pjsip_configs
          SET value='{{ cert_path }}'
          WHERE field='cert_file'
            AND TRIM(`group`)='transport';
        "

    - name: Atualizar priv_key_file no grupo transport
      command: >
        mysql -u {{ lookup('env', 'DB_USER') }}
        -p{{ lookup('env', 'DB_PASSWORD') }}
        -D {{ db_name }}
        -e "
          UPDATE pjsip_configs
          SET value='{{ key_path }}'
          WHERE field='priv_key_file'
            AND TRIM(`group`)='transport';
        "

    - name: Mostrar o que foi aplicado
      debug:
        msg:
          - "cert_file atualizado para: {{ cert_path }}"
          - "priv_key_file atualizado para: {{ key_path }}"
