---
- name: Garantir renovação automática do Certbot em Rocky 8
  hosts: all
  gather_facts: no

  tasks:

    - name: Verificar se o timer existe
      ansible.builtin.stat:
        path: /usr/lib/systemd/system/certbot-renew.timer
      register: timer_file

    - name: Falhar se o timer não existir
      ansible.builtin.fail:
        msg: "❌ Timer certbot-renew.timer não existe nesta máquina!"
      when: not timer_file.stat.exists

    - name: Verificar status do timer
      ansible.builtin.command: systemctl is-active certbot-renew.timer
      register: timer_active
      changed_when: false
      failed_when: false

    - name: Verificar se está habilitado
      ansible.builtin.command: systemctl is-enabled certbot-renew.timer
      register: timer_enabled
      changed_when: false
      failed_when: false

    - name: Habilitar timer se necessário
      ansible.builtin.command: systemctl enable certbot-renew.timer
      when: timer_enabled.stdout != "enabled"

    - name: Iniciar timer se estiver inativo
      ansible.builtin.command: systemctl start certbot-renew.timer
      when: timer_active.stdout != "active"

    - name: Status final
      ansible.builtin.command: systemctl status certbot-renew.timer
      register: final_status
      changed_when: false

    - name: Mostrar resultado final
      ansible.builtin.debug:
        msg:
          - "STATUS FINAL:"
          - "{{ final_status.stdout }}"
