---
- name: Garantir renovação automática do Certbot no Rocky 8 (modo direto)
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Reload no systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Habilitar e iniciar timer correto do Certbot
      ansible.builtin.command: systemctl enable --now certbot.timer

    - name: Restart no timer do Certbot
      ansible.builtin.command: systemctl restart certbot.timer

    - name: Rodar renovação agora (opcional, sobe se o prazo tiver perto)
      ansible.builtin.command: certbot renew --quiet
      ignore_errors: yes

    - name: Status final do timer
      ansible.builtin.command: systemctl status certbot.timer
      register: final_status
      changed_when: false

    - name: Resultado
      ansible.builtin.debug:
        msg:
          - "STATUS TIMER:"
          - "{{ final_status.stdout }}"
