---
- name: Restart e consultar agendamento do Certbot Renew
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Reload no systemd
      ansible.builtin.command: systemctl daemon-reload

    - name: Restart certbot-renew.timer
      ansible.builtin.command: systemctl restart certbot-renew.timer

    - name: Ver quando o Certbot vai rodar
      ansible.builtin.command: systemctl list-timers --all
      register: timers
      changed_when: false

    - name: Filtrar apenas o certbot-renew.timer
      set_fact:
        certbot_timer_info: "{{ timers.stdout_lines | select('search', 'certbot-renew.timer') | list | first }}"
    
    - name: Mostrar informação do próximo renew
      ansible.builtin.debug:
        msg: "⏰ Próxima execução agendada: {{ certbot_timer_info }}"
