---
- name: Gerar certificado Let's Encrypt
  hosts: all
  become: yes
  tasks:
    - name: Executar comando certbot completo
      shell: |
        DOMINIO=$(cat /etc/hostname | sed 's/-/./g').com.br
        sudo certbot --nginx -d $DOMINIO --email cerficados@uniontelecom.com.br --agree-tos --non-interactive
      args:
        warn: false
