- name: Gerar e aplicar certificado Let's Encrypt no Asterisk
  hosts: all
  become: yes
  vars:
    dominio_base: ".com.br"
    lets_dir: "/etc/letsencrypt"
    asterisk_http_conf: "/etc/asterisk/http.conf"
    asterisk_pjsip_conf: "/etc/asterisk/pjsip_transport.conf"

  tasks:
    - name: Instalar dependências
      dnf:
        name:
          - epel-release
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Definir domínio baseado no hostname (minúsculo)
      set_fact:
        dominio: "{{ (ansible_hostname | replace('-', '.')) | lower }}{{ dominio_base }}"

    - name: Gerar certificado Let's Encrypt
      command:
        cmd: >
          certbot --nginx
          -d {{ dominio }}
          --email certificados@uniontelecom.com.br
          --agree-tos
          --non-interactive
      args:
        creates: "{{ lets_dir }}/live/{{ dominio }}/fullchain.pem"

    - name: Ajustar permissões da pasta Let's Encrypt
      file:
        path: "{{ lets_dir }}"
        owner: uscall
        group: uscall
        recurse: yes

    # --- Atualização do http.conf ---
    - name: Atualizar caminho do certificado no http.conf
      lineinfile:
        path: "{{ asterisk_http_conf }}"
        regexp: '^tlscertfile='
        line: "tlscertfile={{ lets_dir }}/live/{{ dominio }}/fullchain.pem"

    - name: Atualizar caminho da chave no http.conf
      lineinfile:
        path: "{{ asterisk_http_conf }}"
        regexp: '^tlsprivatekey='
        line: "tlsprivatekey={{ lets_dir }}/live/{{ dominio }}/privkey.pem"

    # --- Atualização dos campos cert_file e priv_key_file nas seções [tls] e [tls6] ---
    - name: Garantir cert_file em [tls]
      ini_file:
        path: "{{ asterisk_pjsip_conf }}"
        section: tls
        option: cert_file
        value: "{{ lets_dir }}/live/{{ dominio }}/fullchain.pem"

    - name: Garantir priv_key_file em [tls]
      ini_file:
        path: "{{ asterisk_pjsip_conf }}"
        section: tls
        option: priv_key_file
        value: "{{ lets_dir }}/live/{{ dominio }}/privkey.pem"

    - name: Garantir cert_file em [tls6]
      ini_file:
        path: "{{ asterisk_pjsip_conf }}"
        section: tls6
        option: cert_file
        value: "{{ lets_dir }}/live/{{ dominio }}/fullchain.pem"

    - name: Garantir priv_key_file em [tls6]
      ini_file:
        path: "{{ asterisk_pjsip_conf }}"
        section: tls6
        option: priv_key_file
        value: "{{ lets_dir }}/live/{{ dominio }}/privkey.pem"

    - name: Configurar cron para renovação automática
      cron:
        name: "Renovar certificados Let's Encrypt"
        job: "certbot renew --quiet && systemctl reload nginx && systemctl restart asterisk"
        hour: 3
        minute: 0
        user: root

    - name: Reiniciar Asterisk
      systemd:
        name: asterisk
        state: restarted
