- name: Migration playbook
  hosts: all
  become: true
  tasks:
    - name: Copiar wizard.sh para o host
      copy:
        src: files/wizard.sh
        dest: /tmp/wizard.sh
        mode: '0755'

    - name: Copiar records.sh para o host
      copy:
        src: files/records.sh
        dest: /tmp/records.sh
        mode: '0644'
