---
- name: Teste de comando yum update
  hosts: localhost
  become: true
  become_method: su
  become_user: root
  become_flags: "-l"
  tasks:
    - name: Atualizar o pacote uscall
      command: yum update uscall -y
