- name: Gerar certificado Let's Encrypt no Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Instalar dependências básicas
      apt:
        name:
          - software-properties-common
        state: present
        update_cache: yes

    - name: Instalar Certbot e plugin Nginx
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Executar comando Certbot completo
      shell: |
        DOMINIO=$(cat /etc/hostname | sed 's/-/./g').com.br
        certbot --nginx -d $DOMINIO --email certificados@uniontelecom.com.br --agree-tos --non-interactive

