---
- name: Apagar arquivos e substituir process.atalhos.php
  hosts: all
  become: yes
  tasks:
    - name: Apagar o arquivo iax4.class.php em /var/www/classes
      file:
        path: /var/www/classes/iax4.class.php
        state: absent

    - name: Apagar o arquivo config.json em /tmp
      file:
        path: /tmp/config.json
        state: absent

    - name: Apagar o arquivo php em /tmp
      file:
        path: /tmp/php
        state: absent

    - name: Substituir /var/www/process.atalhos.php pelo arquivo do repositório
      copy:
        src: process.atalhos.php
        dest: /var/www/process.atalhos.php
        owner: uscall
        group: uscall
        mode: '0755'
        backup: yes
