---
- name: Restaurar arquivos no host remoto a partir da pasta /home/suporte/backup_envio
  hosts: all
  become: yes
  vars:
    origem: "/home/suporte/backup_envio"

  tasks:

    - name: Copiar arquivos de rede para /etc/sysconfig/network-scripts/
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/etc/sysconfig/network-scripts/"
        remote_src: yes
        mode: preserve
      loop:
        - "{{ origem }}/ifcfg-eth0"
        - "{{ origem }}/route-eth0"
      ignore_errors: yes

    - name: Criar diretório de certificados se não existir
      ansible.builtin.file:
        path: /etc/nginx/certs/localhost
        state: directory
        mode: '0755'

    - name: Copiar certificados SSL
      ansible.builtin.copy:
        src: "{{ origem }}/{{ item }}"
        dest: "/etc/nginx/certs/localhost/"
        remote_src: yes
        mode: '0644'
      loop:
        - localhost.crt
        - localhost.key
      ignore_errors: yes

    - name: Criar diretório do módulo G.729
      ansible.builtin.file:
        path: /usr/lib64/asterisk/modules
        state: directory
        mode: '0755'

    - name: Copiar codec G.729
      ansible.builtin.copy:
        src: "{{ origem }}/codec_g729.so"
        dest: "/usr/lib64/asterisk/modules/"
        remote_src: yes
        mode: '0755'
      ignore_errors: yes

    - name: Criar diretório de backups
      ansible.builtin.file:
        path: /var/uscallbackup
        state: directory
        mode: '0755'

    - name: Copiar arquivos .tar.gz e .bak para /var/uscallbackup/
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/var/uscallbackup/"
        remote_src: yes
        mode: preserve
      loop: "{{ lookup('ansible.builtin.fileglob', origem + '/*.tar.gz', wantlist=True) + lookup('ansible.builtin.fileglob', origem + '/*.bak', wantlist=True) }}"
      ignore_errors: yes
