---
- name: Restaurar arquivos de configuração e backup
  hosts: all
  become: yes
  vars:
    origem: "/home/suporte/backup_envio"

  tasks:

    - name: Copiar arquivos de rede
      ansible.builtin.shell: |
        cp -f {{ origem }}/ifcfg-* {{ origem }}/route-* /etc/sysconfig/network-scripts/ 2>/dev/null

    - name: Copiar certificados SSL
      ansible.builtin.shell: |
        cp -f {{ origem }}/localhost.crt /etc/nginx/certs/localhost/ 2>/dev/null
        cp -f {{ origem }}/localhost.key /etc/nginx/certs/localhost/ 2>/dev/null

    - name: Copiar arquivos de backup (.tar.gz)
      ansible.builtin.shell: |
        cp -f {{ origem }}/*.tar.gz /var/uscallbackup/ 2>/dev/null

    - name: Exibir status final
      ansible.builtin.debug:
        msg: "[✓] Arquivos copiados e substituídos com sucesso."
