---
- name: Adicionar UNION no firewall
  hosts: all
  become: yes

  vars:
    firewall_lines: |
      # === REDES UNION ===
      UNION01=186.224.193.0/24
      UNION02=172.20.0.0/16
      UNION03=10.9.0.0/16

      iptables -I INPUT -s $UNION01 -j ACCEPT
      iptables -I INPUT -s $UNION02 -j ACCEPT
      iptables -I INPUT -s $UNION03 -j ACCEPT
      # === FIM REDES UNION ===

  tasks:

    - name: Inserir bloco UNION logo após LAN=eth0
      blockinfile:
        path: /etc/uscalluc/firewall
        insertafter: "^LAN=eth0"
        block: "{{ firewall_lines }}"
        marker: ""        # REMOVE BEGIN/END
   
    - name: Comentar regra da porta 8222
      replace:
        path: /etc/uscalluc/firewall
        regexp: '^iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'
        replace: '#iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'

    - name: Restart firewall via systemctl
      shell: systemctl restart firewall
