---
- name: Restringir SSH apenas para redes UNION
  hosts: all
  become: yes

  tasks:

    - name: Remover blocos antigos SSH UNION
      blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE UNION SSH"
        state: absent

    - name: Adicionar restricao SSH por rede
      blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE UNION SSH"

        block: |

          Match Address 186.224.193.0/24,172.20.0.0/16,10.9.0.0/16
              PasswordAuthentication yes
              PubkeyAuthentication yes

          Match all
              PasswordAuthentication no
              PubkeyAuthentication no

    - name: Validar configuracao SSH
      shell: sshd -t
      register: sshd_test
      changed_when: false

    - name: Reiniciar SSHD
      service:
        name: sshd
        state: restarted
      when: sshd_test.rc == 0
