---
- name: Adicionar bloco UNION no lugar correto
  hosts: all
  become: yes

  tasks:

    - name: Adicionar bloco UNION antes de #BYPASSSTART
      lineinfile:
        path: /etc/uscalluc/firewall
        insertbefore: "^#BYPASSSTART"
        line: |
          # === REDES UNION ===
          UNION01=186.224.193.0/24
          UNION02=172.20.0.0/16
          UNION03=10.9.0.0/16

          iptables -I INPUT -s $UNION01 -j ACCEPT
          iptables -I INPUT -s $UNION02 -j ACCEPT
          iptables -I INPUT -s $UNION03 -j ACCEPT
          # === FIM REDES UNION ===

    - name: Comentar porta 8222
      replace:
        path: /etc/uscalluc/firewall
        regexp: '^[# ]*iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'
        replace: '#iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'

    - name: Restart firewall
      shell: systemctl restart firewall
      args:
        executable: /bin/bash
