---
- name: Restringir acesso SSH 8222 para redes UNION
  hosts: all
  become: yes

  tasks:

    - name: Remover bloco antigo ANSIBLE UNION SSH
      blockinfile:
        path: /etc/uscalluc/firewall
        marker: "# {mark} ANSIBLE UNION SSH"
        state: absent

    - name: Adicionar regras SSH 8222 no FINAL do firewall
      blockinfile:
        path: /etc/uscalluc/firewall
        insertafter: "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT"
        marker: "# {mark} ANSIBLE UNION SSH"

        block: |

          # === RESTRICAO SSH 8222 UNION ===

          # Remove regras antigas da 8222
          iptables -D INPUT -p tcp --dport 8222 -j ACCEPT 2>/dev/null || true
          iptables -D INPUT -p tcp --dport 8222 -j DROP 2>/dev/null || true

          # Libera somente redes UNION
          iptables -A INPUT -p tcp -s 186.224.193.0/24 --dport 8222 -j ACCEPT
          iptables -A INPUT -p tcp -s 172.20.0.0/16 --dport 8222 -j ACCEPT
          iptables -A INPUT -p tcp -s 10.9.0.0/16 --dport 8222 -j ACCEPT

          # Bloqueia qualquer outro IP
          iptables -A INPUT -p tcp --dport 8222 -j DROP

          # === FIM RESTRICAO SSH 8222 UNION ===

    - name: Comentar regra antiga da 8222
      replace:
        path: /etc/uscalluc/firewall
        regexp: '^[# ]*iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'
        replace: '#iptables -A INPUT -p tcp --dport 8222 -j ACCEPT'

    - name: Restart firewall
      shell: |
        systemctl restart firewall
      args:
        executable: /bin/bash
