---
- name: Adicionar UNION no firewall
  hosts: all
  become: yes

  vars:
    firewall_lines: |
      # === UNION NETWORKS ===
      UNION01=186.224.193.0/24
      UNION02=172.20.0.0/16
      UNION03=10.9.0.0/16

      iptables -I INPUT -s $UNION01 -j ACCEPT
      iptables -I INPUT -s $UNION02 -j ACCEPT
      iptables -I INPUT -s $UNION03 -j ACCEPT
      # === END UNION NETWORKS ===

  tasks:

    - name: Inserir bloco UNION logo após LAN=eth0
      blockinfile:
        path: /etc/uscalluc/firewall
        insertafter: "^LAN=eth0"
        block: "{{ firewall_lines }}"
        marker: "# {mark}"

    - name: Restart firewall via systemctl
      shell: systemctl restart firewall
