---
- name: Atualizar OpenSSH para 9.8p1 via compilação (Ubuntu e Rocky)
  hosts: all
  become: true
  gather_facts: true
  vars:
    openssh_version: "9.8p1"
    src_dir: "/usr/local/src/openssh-src"
    build_dir: "{{ src_dir }}/openssh-{{ openssh_version }}"
    openssh_url: "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-{{ openssh_version }}.tar.gz"

  tasks:
    - name: Instalar dependências no Ubuntu
      apt:
        name:
          - build-essential
          - zlib1g-dev
          - libssl-dev
          - libpam0g-dev
          - wget
          - tar
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Instalar dependências no Rocky/CentOS/RHEL
      dnf:
        name:
          - gcc
          - make
          - zlib-devel
          - openssl-devel
          - pam-devel
          - wget
          - tar
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Criar diretório de fontes
      file:
        path: "{{ src_dir }}"
        state: directory
        mode: '0755'

    - name: Baixar código-fonte do OpenSSH
      get_url:
        url: "{{ openssh_url }}"
        dest: "{{ src_dir }}/openssh-{{ openssh_version }}.tar.gz"

    - name: Descompactar o código-fonte
      unarchive:
        src: "{{ src_dir }}/openssh-{{ openssh_version }}.tar.gz"
        dest: "{{ src_dir }}"
        remote_src: yes

    - name: Definir caminho do privsep dependendo da distro
      set_fact:
        privsep_path: "{{ '/var/run/sshd' if ansible_facts['os_family'] == 'Debian' else '/var/lib/sshd' }}"

    - name: Configurar build
      command: >
        ./configure
        --prefix=/usr
        --sysconfdir=/etc/ssh
        --with-md5-passwords
        --with-pam
        --with-privsep-path={{ privsep_path }}
      args:
        chdir: "{{ build_dir }}"

    - name: Compilar o OpenSSH
      command: make
      args:
        chdir: "{{ build_dir }}"

    - name: Instalar o OpenSSH
      command: make install
      args:
        chdir: "{{ build_dir }}"

    - name: Criar diretório de privsep
      file:
        path: "{{ privsep_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Garantir que o UsePAM esteja configurado corretamente
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UsePAM'
        line: 'UsePAM yes'
        create: yes
        state: present

    - name: Reiniciar o serviço sshd (Ubuntu)
      systemd:
        name: ssh
        state: restarted
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Reiniciar o serviço sshd (Rocky)
      systemd:
        name: sshd
        state: restarted
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"
