---
- name: Instalação do OpenSSH 9.8p1 com suporte a GSSAPI
  hosts: all
  become: yes

  vars:
    openssh_version: "9.8p1"
    openssh_tarball: "openssh-{{ openssh_version }}.tar.gz"
    openssh_url: "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/{{ openssh_tarball }}"
    openssh_dir: "/usr/local/src/openssh-{{ openssh_version }}"

  tasks:
    - name: Instalar dependências de compilação
      package:
        name:
          - gcc
          - make
          - zlib-devel
          - openssl-devel
          - pam-devel
          - krb5-devel
          - wget
        state: present

    - name: Baixar o OpenSSH
      get_url:
        url: "{{ openssh_url }}"
        dest: "/usr/local/src/{{ openssh_tarball }}"

    - name: Extrair o OpenSSH
      unarchive:
        src: "/usr/local/src/{{ openssh_tarball }}"
        dest: "/usr/local/src/"
        remote_src: yes

    - name: Configurar o OpenSSH com suporte ao GSSAPI
      command: ./configure --prefix=/usr --sysconfdir=/etc/ssh --with-pam --with-kerberos5 --with-md5-passwords --with-ssl-engine
      args:
        chdir: "{{ openssh_dir }}"

    - name: Compilar o OpenSSH
      make:
        chdir: "{{ openssh_dir }}"

    - name: Instalar o OpenSSH
      make:
        chdir: "{{ openssh_dir }}"
        target: install

    - name: Garantir que o arquivo sshd_config existe
      file:
        path: /etc/ssh/sshd_config
        state: touch

    - name: Configurar o sshd_config com suporte ao GSSAPI
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Protocol 2
          PermitRootLogin yes
          PasswordAuthentication yes
          ChallengeResponseAuthentication no
          UsePAM yes
          GSSAPIAuthentication yes
          GSSAPICleanupCredentials yes
          GSSAPIKeyExchange yes
          GSSAPIKexAlgorithms gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-,gss-gex-sha1-,gss-group14-sha1-
          UseDNS no
          AllowTcpForwarding yes
          X11Forwarding yes
          Subsystem sftp /usr/libexec/sftp-server

    - name: Reiniciar o serviço SSH
      systemd:
        name: sshd
        state: restarted
        enabled: yes
