---
- name: Atualizar OpenSSH para 9.8p1 no Rocky Linux 8
  hosts: all
  become: true
  vars:
    openssh_version: "9.8p1"
    src_dir: "/usr/local/src/openssh-src"
    build_dir: "{{ src_dir }}/openssh-{{ openssh_version }}"
    openssh_url: "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-{{ openssh_version }}.tar.gz"

  tasks:

    - name: Instalar dependências de compilação
      dnf:
        name:
          - gcc
          - make
          - zlib-devel
          - openssl-devel
          - pam-devel
          - wget
        state: present

    - name: Criar diretório de fontes
      file:
        path: "{{ src_dir }}"
        state: directory
        mode: 0755

    - name: Baixar OpenSSH {{ openssh_version }}
      get_url:
        url: "{{ openssh_url }}"
        dest: "{{ src_dir }}/openssh-{{ openssh_version }}.tar.gz"
        mode: 0644

    - name: Descompactar o código-fonte
      unarchive:
        src: "{{ src_dir }}/openssh-{{ openssh_version }}.tar.gz"
        dest: "{{ src_dir }}"
        remote_src: yes

    - name: Configurar o OpenSSH
      command: ./configure --prefix=/usr --sysconfdir=/etc/ssh --with-md5-passwords --with-pam
      args:
        chdir: "{{ build_dir }}"

    - name: Compilar o OpenSSH
      command: make
      args:
        chdir: "{{ build_dir }}"

    - name: Instalar o OpenSSH
      command: make install
      args:
        chdir: "{{ build_dir }}"
      notify: Reiniciar sshd

    - name: Corrigir permissões das chaves privadas SSH
      file:
        path: "{{ item }}"
        mode: '0600'
        owner: root
        group: root
      loop:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ed25519_key
      notify: Reiniciar sshd

    - name: Corrigir permissões das chaves públicas SSH
      file:
        path: "{{ item }}"
        mode: '0644'
        owner: root
        group: root
      loop:
        - /etc/ssh/ssh_host_rsa_key.pub
        - /etc/ssh/ssh_host_ecdsa_key.pub
        - /etc/ssh/ssh_host_ed25519_key.pub

    - name: Remover linha com GSSAPIKexAlgorithms do openssh.config
      lineinfile:
        path: /etc/crypto-policies/back-ends/openssh.config
        regexp: '^GSSAPIKexAlgorithms'
        state: absent
      notify: Reiniciar sshd

    - name: Remover linha com GSSAPIAuthentication do 05-redhat.conf
      lineinfile:
        path: /etc/ssh/ssh_config.d/05-redhat.conf
        regexp: '^GSSAPIAuthentication'
        state: absent
      notify: Reiniciar sshd

  handlers:
    - name: Reiniciar sshd
      systemd:
        name: sshd
        state: restarted
