---
- name: Instalar OpenSSH 9.8p1 no Rocky Linux 8
  hosts: all
  become: true
  vars:
    openssh_versao: "9.8p1"
    openssh_src_dir: "/usr/local/src/openssh-{{ openssh_versao }}"
    openssh_tarball: "openssh-{{ openssh_versao }}.tar.gz"
    openssh_url: "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/{{ openssh_tarball }}"

  tasks:
    - name: Instalar dependências
      dnf:
        name:
          - gcc
          - make
          - pam-devel
          - zlib-devel
          - openssl-devel
          - krb5-devel
          - wget
        state: present

    - name: Baixar o OpenSSH {{ openssh_versao }}
      get_url:
        url: "{{ openssh_url }}"
        dest: "/usr/local/src/{{ openssh_tarball }}"

    - name: Extrair o código-fonte do OpenSSH
      unarchive:
        src: "/usr/local/src/{{ openssh_tarball }}"
        dest: "/usr/local/src"
        remote_src: yes

    - name: Configurar a compilação com GSSAPI
      command: ./configure --with-md5-passwords --with-kerberos5 --with-pam --with-gssapi
      args:
        chdir: "{{ openssh_src_dir }}"

    - name: Compilar o OpenSSH
      command: make
      args:
        chdir: "{{ openssh_src_dir }}"

    - name: Instalar o OpenSSH
      command: make install
      args:
        chdir: "{{ openssh_src_dir }}"

    - name: Criar diretório do serviço SSH caso não exista
      file:
        path: /var/run/sshd
        state: directory
        mode: '0755'

    - name: Garantir que o SSHD está configurado com GSSAPI
      blockinfile:
        path: /usr/local/etc/sshd_config
        block: |
          GSSAPIAuthentication yes
          GSSAPICleanupCredentials yes
          GSSAPIKeyExchange yes
          PermitRootLogin yes
          PasswordAuthentication yes

    - name: Criar serviço systemd do OpenSSH
      copy:
        dest: /etc/systemd/system/sshd-local.service
        content: |
          [Unit]
          Description=OpenSSH Daemon Personalizado
          After=network.target

          [Service]
          ExecStart=/usr/local/sbin/sshd -D
          ExecReload=/bin/kill -HUP $MAINPID
          KillMode=process
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Recarregar systemd
      command: systemctl daemon-reexec

    - name: Ativar e iniciar serviço SSHD personalizado
      systemd:
        name: sshd-local
        enabled: true
        state: restarted
