---
- name: OPEN VMTOOLS INSTALL
  become: yes
  hosts: all
  tasks:
    - name: Install OPEN VM TOOLS PACKAGE
      command: yum install open-vm-tools -y
    - name: REBOOT AFTER INSTALL 
      reboot: 
        reboot_timeout: 600

